const products = [
  {
    sku: "STD-TBL-WTH-RCK",
    name: "Study Table with rack",
    image1: "i am a image",
    brand: "OATH DIGITAL INDIA",
    category: "",
    price: 20000,
    countInStock: 20,
    salePrice: 16000,
    description:
      "Study tables are plain and simple tables that are used or studying or writing purposes. Depending on the size of the room or the place where you want to place it you can get large l shaped study tables or rectangular or L-shaped ones.Thus, study tables are meant for almost all age groups",
    backOrder: false,
    isActive: true,
  },
  {
    sku: "STD-TBL-WTH-5",
    name: "Study Table with 5 Droll",
    image1: "i am a image",
    brand: "OATH DIGITAL INDIA",
    category: "",
    price: 19999,
    countInStock: 20,
    salePrice: 13999,
    description:
      "1. With a wealth of storage space, Nettle has space for everything from small stationery items to your books. This unit is designed to keep a perfect balance of functionality and aesthetics. 2. Nettle is crafted from solid wood, which can be identified with the grained pattern over the surface of this study table. ​3. It is available in different finish options, which can revamp the look of your study interiors.",
    backOrder: true,
    isActive: true,
  },
  {
    sku: "STD-TBL-WTH-3",
    name: "Study Table with 3 Droll",
    image1: "i am a image",
    brand: "OATH DIGITAL INDIA",
    category: "",
    price: 16000,
    countInStock: 20,
    salePrice: 7099,
    description:
      "1. With a wealth of storage space, Nettle has space for everything from small stationery items to your books. This unit is designed to keep a perfect balance of functionality and aesthetics. 2. Nettle is crafted from solid wood, which can be identified with the grained pattern over the surface of this study table. ​3. It is available in different finish options, which can revamp the look of your study interiors.",
    backOrder: false,
    isActive: true,
  },
  {
    sku: "STD-TBL-WTH-3-AS-PER-VRB",
    name: "Study Table with 3 Droll",
    image1: "i am a image",
    brand: "OATH DIGITAL INDIA",
    category: "STD-TBL-WTH-3",
    price: 16000,
    countInStock: 20,
    salePrice: 7099,
    description: "desc required",
    backOrder: false,
    isActive: true,
  },
  {
    sku: "STD-TBL-WTH",
    name: "Study Table with rack",
    image1: "i am a image",
    brand: "OATH DIGITAL INDIA",
    category: "",
    price: 20000,
    countInStock: 20,
    salePrice: 15999,
    description:
      "Study tables are plain and simple tables that are used or studying or writing purposes. Depending on the size of the room or the place where you want to place it you can get large l shaped study tables or rectangular or L-shaped ones.Thus, study tables are meant for almost all age groups",
    backOrder: false,
    isActive: true,
  },
  {
    sku: "VRT-3D-VW-MLT",
    name: "vertical 3D view multi plants svp1",
    image1: "i am a image",
    brand: "OATH DIGITAL INDIA",
    category: "",
    price: 45000,
    countInStock: 20,
    salePrice: 35000,
    description:
      "The design of these rectangular plant pots evokes lamps emitting vegetation. The plastic inner plate and pot are offered.",
    backOrder: false,
    isActive: true,
  },
  {
    sku: "VRT-3D-VW-MLT-ANY",
    name: "vertical 3D view multi plants svp1",
    image1: "i am a image",
    brand: "OATH DIGITAL INDIA",
    category: "VRT-3D-VW-MLT",
    price: 45000,
    countInStock: 20,
    salePrice: 35000,
    description: "desc required",
    backOrder: false,
    isActive: true,
  },
  {
    sku: "STD-TBL-CNN-WTH",
    name: "Study table connecting with one rack",
    image1: "i am a image",
    brand: "OATH DIGITAL INDIA",
    category: "",
    price: 15000,
    countInStock: 20,
    salePrice: 9000,
    description:
      "Brighten up your space with unique & stylish furniture. Premium Quality. Great Value.",
    backOrder: false,
    isActive: true,
  },
  {
    sku: "SF-CUM-BED-RNK",
    name: "Sofa cum bed rank1",
    image1: "i am a image",
    brand: "OATH DIGITAL INDIA",
    category: "",
    price: 60000,
    countInStock: 20,
    salePrice: 32499,
    description:
      "Sofa Cum Bed with Adjustable Headrest & Storage Dimensions: Sofa: H 29 x W 54 x D 36; Lounger size: H 29 x W 32 x D 67; Bed Size When Open: H 17 x W 75.5 x D 54; Storage Size: H 10 x W 23.5 x D 65; Seating Height: 17; Seating Depth: 22 (all dimension are in inches) ( NOTE- AS PER CUSTOMER DEMAND )* Weight: NA Warranty: 12 Months' Warranty Assembly: No Assembly Required Primary Material: Fabric Room Type: Living Room Storage: With Storage Seating Height: NA Specifications : Upholstery: Fabric Inner Frame: Red Meranti Solid Wood Foam Density: 32 to 40 Disclaimers: Accessories shown in the image are only for representation and are not part of the product. Depending on your screen settings and resolution on your device there may be a slight variance in fabric colour and wood polish of the image and actual product. Wood grains will vary from product to product in case of solid wood furniture. Furniture having intricate hand-painted details are individual unique pieces and may have slight distinctions and variance between the picture and actual product. The Primary material is the main material used to manufacture the product and in addition to the primary material there might also be other types of materials",
    backOrder: false,
    isActive: true,
  },
  {
    sku: "SF-CUM-BED-RNK-ANY",
    name: "Sofa cum bed rank1",
    image1: "i am a image",
    brand: "OATH DIGITAL INDIA",
    category: "SF-CUM-BED-RNK",
    price: 60000,
    countInStock: 20,
    salePrice: 32499,
    description: "desc required",
    backOrder: false,
    isActive: true,
  },
  {
    sku: "SF-SET-3-1",
    name: "Sofa Set (3+1+1) oath5",
    image1: "i am a image",
    brand: "OATH DIGITAL INDIA",
    category: "",
    price: 65000,
    countInStock: 20,
    salePrice: 38000,
    description:
      "Give your home a captivating make-over with this textured sofa set, that has been designed to impart a comfortable and sleek look to your home.The Sofa is upholstered with polyester fabric which is synthetic and easily recyclable. It also comes with high tensile strength and durability to last much longer. Being chemical generated these fabrics are naturally anti-bacterial.The sofa features a combination of pocket spring & high-resilience foam in the seats to provide suitable comfort. No-sag springs are used in the construction of the sofa. The backrest comes with high-elastic nylon webbing for greater support & comfort.The sofa also has solid wood legs for greater strength and longer durability.The Sofa upholstery is resistant to growth and spread of microorganisms, thus, making it more hygienic to use for a longer duration. It is also resistant to static charges being produced due to friction of the human body and upholstery and makes it skin-friendly material.The Sofa Upholstery comes with non-woven fabric backing which becomes fuller and increases the tensile strength and dimensional stability. Dimensions: 3 Seater: H 34.64 x W 72.44 x D 36.22; 1 Seater: H 34.64 x W 32.28 x D 36.22; Seating Height 17.32 (All dimensions are in inches) Weight: Na Warranty: 12 Months' Warranty Assembly: Assembly by Brand Primary Material: Fabric Room Type: Living Room Seating Height: Na Specifications : High Resilience. The sofa set is upholstered with polyester fabric which is easily recyclable with high tensile strength and durability, making it last much longer. Built from a strong frame that is durable and long-lasting. Upholstery Material: Polyester Primary Material: Solid Wood Seat Filling: Foam Wood type: Meranti wood Design: Textured.",
    backOrder: false,
    isActive: true,
  },
  {
    sku: "SF-SET-3-1-ANY-LRG",
    name: "Sofa Set (3+1+1) oath5",
    image1: "i am a image",
    brand: "OATH DIGITAL INDIA",
    category: "SF-SET-3-1",
    price: 65000,
    countInStock: 20,
    salePrice: 38999,
    description: "desc required",
    backOrder: false,
    isActive: true,
  },
  {
    sku: "SF-SET-3-1-ANY-MDM",
    name: "Sofa Set (3+1+1) oath5",
    image1: "i am a image",
    brand: "OATH DIGITAL INDIA",
    category: "SF-SET-3-1",
    price: 65000,
    countInStock: 20,
    salePrice: 38999,
    description: "desc required",
    backOrder: false,
    isActive: true,
  },
  {
    sku: "SF-SET-3-1-ANY-SML",
    name: "Sofa Set (3+1+1) oath5",
    image1: "i am a image",
    brand: "OATH DIGITAL INDIA",
    category: "SF-SET-3-1",
    price: 65000,
    countInStock: 20,
    salePrice: 38000,
    description: "desc required",
    backOrder: false,
    isActive: true,
  },
  {
    sku: "SF-SET-3-2",
    name: "sofa set ( 3+2 ) oath5",
    image1: "i am a image",
    brand: "OATH DIGITAL INDIA",
    category: "",
    price: 48000,
    countInStock: 20,
    salePrice: 36999,
    description:
      "Sofa Set (3+2) Dimensions: 3 Seater: H 34.64 x W 72.44 x D 36.22; 2 Seater: H 34.64 x W 52.36 x D 36.22; Seating Height 17.32 (All dimensions are in inches) Weight: Na Warranty: 12 Months' Warranty Assembly: Assembly by Brand Primary Material: Fabric Room Type: Living Room Seating Height: Na",
    backOrder: false,
    isActive: true,
  },
  {
    sku: "SF-SET-3-2-ANY",
    name: "sofa set ( 3+2 ) oath5",
    image1: "i am a image",
    brand: "OATH DIGITAL INDIA",
    category: "SF-SET-3-2",
    price: 48000,
    countInStock: 20,
    salePrice: 36999,
    description: "desc required",
    backOrder: false,
    isActive: true,
  },
];

module.exports = products
